### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by antonlep** [JVS23/ot-harjoitustyo#1]
Koodi ladattu 13.12. klo 16

Huomioita:
- Funktiot, metodit ja muuttujat on nimetty selkeästi ja johdonmukaisesti
- main - funktio on melko pitkä , kuten oli kommentissa mainittukin
- Ehkä main - funktion if-rakenteelle voisi miettiä tiiviimpää vaihtoehtoa, esim dictionaryyn perustuva tai uusi luokka
- Käyttöliittymä ja sovelluslogiikka voisi ehkä enemmän eriyttää, esim tulostusta ja käyttäjä inputin käsittelyä siirtää pois Player ja Dice luokista
- Muuten yksittäiset metodit hoitavat johdonmukaisesti yhtä asiaa
- Koodi on jaettu loogisiin luokkiin, joilla on omat vastuualueet (Noppa, pelaaja, pistelaskulogiikka)
- Jokainen luokka testataan selkeästi omassa tiedostossaan ja testit testaavat järkevää toiminnalisuutta
- Ohjelma toimi pääpiirteittäin hyvin, pari huomiota: Tällä hetkellä pystyy laittaa kaksi kertaa pisteet samaan kategoriaan, ja valitessa noppia indeksin mukaan jos valitsee monta numeroa, esim 234, ei ole selkeä mitä tapahtuu, ilmeisesti siirrytään seuraavaan vaiheeseen muuttamatta noppia

**Comment by JVS23** [comment]
Kiitos erinomaisesta palautteesta!
